<img src="img/bannerTermCond.jpg" alt=""/>

<div id="termosCondicoes">
    <div class="separador">
        <hr />
        <img src="img/separador_local.jpg" alt="" />
    </div>
    <h1><span id="normal">Termos </span><span id="semiBold">& </span>Condições</h1>
    <h2>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et nisi nec elit scelerisque suscipit. Proin id rhoncus lacus. Praesent vitae orci lobortis, volutpat neque et, mattis nisi. Phasellus ac tempor nulla, at egestas augue. Praesent eget suscipit nunc. Donec quis rhoncus sapien. Morbi euismod nibh et ullamcorper pretium. Praesent luctus, urna id hendrerit adipiscing, nunc sem ullamcorper tortor, ac auctor dui purus in erat. Cras fringilla, turpis et dictum adipiscing, est nisl imperdiet orci, et congue eros est in tortor. Mauris ultricies metus eros, vel sagittis neque tempus id. Morbi tellus dui, accumsan vitae viverra in, fringilla id nisl. Suspendisse potenti. Donec a placerat massa, in lacinia diam. Fusce ut diam vel risus congue congue pretium quis quam. Nulla orci dui, molestie consequat felis vitae, rutrum dapibus sapien. Nulla facilisi.</p>
    <p>Praesent consequat malesuada turpis, at fringilla est dignissim sit amet. Vivamus at nibh id turpis bibendum tristique a eget lectus. Aliquam venenatis semper nunc, non faucibus turpis cursus vel. Curabitur a metus quis elit malesuada fermentum sed commodo turpis. Maecenas euismod arcu in tellus sagittis tincidunt. Nunc rhoncus, ligula nec fringilla tincidunt, risus mauris faucibus odio, eget blandit lacus ipsum ut lacus. Quisque ultrices arcu non accumsan egestas. Aenean feugiat odio vel dui sagittis lacinia. Nullam faucibus orci ut nibh blandit, tincidunt hendrerit risus varius. Maecenas vulputate placerat purus, at dapibus augue pretium at. Curabitur viverra ac libero sed mattis. Nullam consectetur dui vel diam volutpat dictum. Pellentesque gravida massa ac arcu vulputate, eget interdum eros rutrum. Duis facilisis vestibulum ornare. Suspendisse in nunc quis leo dictum vehicula nec non mauris. Nam iaculis augue tellus, ut bibendum velit aliquam quis.</p>
    <p>Sed et tortor pulvinar, bibendum leo ut, congue enim. Vestibulum posuere, eros sed ullamcorper sollicitudin, orci dui interdum ante, eget blandit nulla turpis et turpis. In non nisl tristique, porttitor elit ut, ultrices diam. In ac posuere augue, vitae mollis mauris. Cras blandit metus enim, in pharetra magna fermentum a. Suspendisse ac risus ultricies, fringilla urna vel, tristique sapien. Fusce lobortis mattis tristique. Proin sed libero magna. Cras pulvinar turpis non ante semper volutpat. Curabitur auctor accumsan auctor. Phasellus at felis congue, gravida dolor at, laoreet lectus. Phasellus hendrerit, neque eu aliquam dapibus, enim sem facilisis neque, eget mollis ligula enim id eros. Mauris tempor pellentesque felis eget fringilla. Cras non sapien ut magna ornare condimentum non sit amet magna. Etiam id ultrices neque, ut tempus dui. Sed tempus commodo augue a fringilla.</p>
</div>